### ISSUE TITLE
[feature request] add a sort array by fieldname

### ISSUE THREAD

**Issue by jadwigo** [GawainLynch/bolt-extension-twig-extensions#1]
can you add a filter like https://bitbucket.org/michaelrog/craftsupersort

so I can do `{% for item in itemarray|sort('itemkey') %}`

When I have an unordered `itemarray` that is:
```json
[
  {"temname": "third", "itemkey": 10},
  {"itemname": "second", "itemkey": 3},
  {"itemname": "first", "itemkey": 1},
  {"itemname": "last", "itemkey": 11}
]
```
and the resulting itemnames will be ordered as `first, second, third, last`

or I can do `{% for item in itemarray|sort('-itemkey') %}`

and the resulting itemnames will be ordered as `last, third, second, first`

**Comment by GawainLynch** [comment]
…and port the extension to Bolt v3 I'd guess too :wink:

**Comment by jadwigo** [comment]
.. you read my mind :)

**Comment by jadwigo** [comment]
owh.. it's already in code if you use a `{% for x in y|sort('key') %}` 

http://cheatsheet.bolt.cm/#the-for-control-structure
